#!/bin/sh
echo "Running code formatter..."
npm run format

if [ $? -ne 0 ]; then
  echo "Code formatting failed. Commit aborted."
  exit 1
fi

echo "Running linter..."
npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Commit aborted."
  exit 1
fi


echo "Running typechecking..."
npm run ts:check

if [ $? -ne 0 ]; then
  echo "Typechecking failed. Commit aborted."
  exit 1
fi
